'use strict';

// Creates a .env for a local demo with random database passwords.
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const target = path.join(__dirname, '..', '.env');
if (fs.existsSync(target)) {
  console.error('.env already exists; delete it first if you want a new one.');
  process.exit(1);
}

const random = () => crypto.randomBytes(16).toString('hex');
const lines = [
  '# Generated by `npm run init-env` for a local demo. Never commit this file.',
  '',
  '# Database (docker compose creates both users from these values)',
  'DB_HOST=127.0.0.1',
  'DB_PORT=3306',
  'DB_NAME=covidweb',
  'DB_USER=covidweb',
  `DB_PASS=${random()}`,
  `DB_ROOT_PASS=${random()}`,
  '',
  '# Map pages (doctors), optional',
  'MAPBOX_TOKEN=',
  'ESRI_API_KEY=',
  '',
  '# Deploy webhook, disabled while the secret is empty',
  'GITHUB_WEBHOOK_SECRET=',
  'DEPLOY_DIR=',
  'DEPLOY_BRANCH=master',
  '',
];
fs.writeFileSync(target, lines.join('\n'), { mode: 0o600 });
console.log('Created .env');
